### ISSUE TITLE
[Survivor Store] Translation error

### ISSUE THREAD

**Issue by AhRoon** [fbef0102/L4D2-Plugins#1]
Hi,

When I install Survivor Store plugin, it gives me an error:
```
L 03/10/2021 - 22:36:07: [SM] Exception reported: Language phrase "Not enough players" not found (arg 5)
L 03/10/2021 - 22:36:07: [SM] Blaming: L4D2_Survivor_Store.smx
L 03/10/2021 - 22:36:07: [SM] Call stack trace:
L 03/10/2021 - 22:36:07: [SM]   [0] ReplyToCommand
L 03/10/2021 - 22:36:07: [SM]   [1] Line 463, test\L4D2_Survivor_Store.sp::BuyShopCommand
```

Can you look and fix the issue?
Thanks.

And no, if you're asking that I removed the translation file, I used your default translation file.

**Comment by fbef0102** [comment]
download again and make sure the translation file exists in the right folder (sourcemod/translations)

**Comment by AhRoon** [comment]
> [download again](https://github.com/fbef0102/L4D2-Plugins/tree/master/L4D2_Survivor_Store) and make sure the translation file exists in the right folder (sourcemod/translations)

Thanks, recent version fixed the issue :)
