### ISSUE TITLE
AI Hard SI plugin errors

### ISSUE THREAD

**Issue by SefoNotasi** [fbef0102/L4D2-Plugins#11]
L 12/03/2022 - 03:06:04: SourceMod error session started
L 12/03/2022 - 03:06:04: Info (map "re2a1") (file "/game/left4dead2/addons/sourcemod/logs/errors_20221203.log")
L 12/03/2022 - 03:06:04: [SM] Exception reported: Client 2 is not connected
L 12/03/2022 - 03:06:04: [SM] Blaming: AI_HardSI.smx
L 12/03/2022 - 03:06:04: [SM] Call stack trace:
L 12/03/2022 - 03:06:04: [SM]   [0] SetUserFlagBits
L 12/03/2022 - 03:06:04: [SM]   [1] Line 455, includes/hardcoop_util.sp::CheatCommand
L 12/03/2022 - 03:06:04: [SM]   [2] Line 72, AI_HardSI.sp::Timer_ForceInfectedAssault
L 12/03/2022 - 03:09:58: [SM] Exception reported: Client 4 is not connected
L 12/03/2022 - 03:09:58: [SM] Blaming: AI_HardSI.smx
L 12/03/2022 - 03:09:58: [SM] Call stack trace:
L 12/03/2022 - 03:09:58: [SM]   [0] SetUserFlagBits
L 12/03/2022 - 03:09:58: [SM]   [1] Line 455, includes/hardcoop_util.sp::CheatCommand
L 12/03/2022 - 03:09:58: [SM]   [2] Line 72, AI_HardSI.sp::Timer_ForceInfectedAssault
L 12/03/2022 - 03:10:04: [SM] Exception reported: Client 8 is not connected
L 12/03/2022 - 03:10:04: [SM] Blaming: AI_HardSI.smx
L 12/03/2022 - 03:10:04: [SM] Call stack trace:
L 12/03/2022 - 03:10:04: [SM]   [0] SetUserFlagBits
L 12/03/2022 - 03:10:04: [SM]   [1] Line 455, includes/hardcoop_util.sp::CheatCommand
L 12/03/2022 - 03:10:04: [SM]   [2] Line 72, AI_HardSI.sp::Timer_ForceInfectedAssault
L 12/03/2022 - 03:10:41: [SM] Exception reported: Client 9 is not connected
L 12/03/2022 - 03:10:41: [SM] Blaming: AI_HardSI.smx
L 12/03/2022 - 03:10:41: [SM] Call stack trace:
L 12/03/2022 - 03:10:41: [SM]   [0] SetUserFlagBits
L 12/03/2022 - 03:10:41: [SM]   [1] Line 455, includes/hardcoop_util.sp::CheatCommand
L 12/03/2022 - 03:10:41: [SM]   [2] Line 72, AI_HardSI.sp::Timer_ForceInfectedAssault
L 12/03/2022 - 11:32:24: Error log file session closed.

**Comment by fbef0102** [comment]
Error line dismatch the version on github, please [redownload ](https://github.com/fbef0102/L4D2-Plugins/tree/master/AI_HardSI)

**Comment by SefoNotasi** [comment]
Redownloaded latest version from here and get ton of same errors:
L 12/16/2022 - 00:18:20: SourceMod error session started
L 12/16/2022 - 00:18:20: Info (map "c11m3_garage") (file "/game/left4dead2/addons/sourcemod/logs/errors_20221216.log")
L 12/16/2022 - 00:18:20: [SM] Exception reported: Client 6 is not connected
L 12/16/2022 - 00:18:20: [SM] Blaming: AI_HardSI.smx
L 12/16/2022 - 00:18:20: [SM] Call stack trace:
L 12/16/2022 - 00:18:20: [SM]   [0] SetUserFlagBits
L 12/16/2022 - 00:18:20: [SM]   [1] Line 442, includes\hardcoop_util.sp::CheatCommand
L 12/16/2022 - 00:18:20: [SM]   [2] Line 73, AI_HardSI.sp::Timer_ForceInfectedAssault
L 12/16/2022 - 00:18:58: [SM] Exception reported: Client 11 is not connected
L 12/16/2022 - 00:18:58: [SM] Blaming: AI_HardSI.smx

Here logs:
[errors_20221216.log](https://github.com/fbef0102/L4D2-Plugins/files/10263838/errors_20221216.log)
[errors_20221217.log](https://github.com/fbef0102/L4D2-Plugins/files/10263839/errors_20221217.log)

**Comment by fbef0102** [comment]
> Redownloaded latest version from here and get ton of same errors: L 12/16/2022 - 00:18:20: SourceMod error session started L 12/16/2022 - 00:18:20: Info (map "c11m3_garage") (file "/game/left4dead2/addons/sourcemod/logs/errors_20221216.log") L 12/16/2022 - 00:18:20: [SM] Exception reported: Client 6 is not connected L 12/16/2022 - 00:18:20: [SM] Blaming: AI_HardSI.smx L 12/16/2022 - 00:18:20: [SM] Call stack trace: L 12/16/2022 - 00:18:20: [SM] [0] SetUserFlagBits L 12/16/2022 - 00:18:20: [SM] [1] Line 442, includes\hardcoop_util.sp::CheatCommand L 12/16/2022 - 00:18:20: [SM] [2] Line 73, AI_HardSI.sp::Timer_ForceInfectedAssault L 12/16/2022 - 00:18:58: [SM] Exception reported: Client 11 is not connected L 12/16/2022 - 00:18:58: [SM] Blaming: AI_HardSI.smx
> 
> Here logs: [errors_20221216.log](https://github.com/fbef0102/L4D2-Plugins/files/10263838/errors_20221216.log) [errors_20221217.log](https://github.com/fbef0102/L4D2-Plugins/files/10263839/errors_20221217.log)

Try this
[AI_HardSI v1.4.zip](https://github.com/fbef0102/L4D2-Plugins/files/10264080/AI_HardSI.v1.4.zip)

**Comment by SefoNotasi** [comment]
Thank you, I will try this version. I'll let you know later if the errors are gone or not.

**Comment by SefoNotasi** [comment]
It worked for a few weeks without errors, but yesterday and today the errors appeared again:

L 01/02/2023 - 14:00:58: SourceMod error session started
L 01/02/2023 - 14:00:58: Info (map "xmas_hotel") (file "/game/left4dead2/addons/sourcemod/logs/errors_20230102.log")
L 01/02/2023 - 14:00:58: [SM] Exception reported: Client 3 is not connected
L 01/02/2023 - 14:00:58: [SM] Blaming: AI_HardSI.smx
L 01/02/2023 - 14:00:58: [SM] Call stack trace:
L 01/02/2023 - 14:00:58: [SM]   [0] SetUserFlagBits
L 01/02/2023 - 14:00:58: [SM]   [1] Line 442, includes\hardcoop_util.sp::CheatCommand
L 01/02/2023 - 14:00:58: [SM]   [2] Line 73, AI_HardSI.sp::Timer_ForceInfectedAssault
L 01/02/2023 - 14:01:23: [SM] Exception reported: Client 5 is not connected
L 01/02/2023 - 14:01:23: [SM] Blaming: AI_HardSI.smx
L 01/02/2023 - 14:01:23: [SM] Call stack trace:
L 01/02/2023 - 14:01:23: [SM]   [0] SetUserFlagBits
L 01/02/2023 - 14:01:23: [SM]   [1] Line 442, includes\hardcoop_util.sp::CheatCommand
L 01/02/2023 - 14:01:23: [SM]   [2] Line 73, AI_HardSI.sp::Timer_ForceInfectedAssault
L 01/02/2023 - 14:01:34: [SM] Exception reported: Client 1 is not connected
L 01/02/2023 - 14:01:34: [SM] Blaming: AI_HardSI.smx
L 01/02/2023 - 14:01:34: [SM] Call stack trace:
L 01/02/2023 - 14:01:34: [SM]   [0] SetUserFlagBits
L 01/02/2023 - 14:01:34: [SM]   [1] Line 442, includes\hardcoop_util.sp::CheatCommand
L 01/02/2023 - 14:01:34: [SM]   [2] Line 73, AI_HardSI.sp::Timer_ForceInfectedAssault
L 01/02/2023 - 14:01:42: [SM] Exception reported: Client 14 is not connected
L 01/02/2023 - 14:01:42: [SM] Blaming: AI_HardSI.smx
L 01/02/2023 - 14:01:42: [SM] Call stack trace:
L 01/02/2023 - 14:01:42: [SM]   [0] SetUserFlagBits
L 01/02/2023 - 14:01:42: [SM]   [1] Line 442, includes\hardcoop_util.sp::CheatCommand
L 01/02/2023 - 14:01:42: [SM]   [2] Line 73, AI_HardSI.sp::Timer_ForceInfectedAssault
L 01/02/2023 - 14:08:04: Error log file session closed.

Full logs:
[errors_20230102.log](https://github.com/fbef0102/L4D2-Plugins/files/10337359/errors_20230102.log)
[errors_20230103.log](https://github.com/fbef0102/L4D2-Plugins/files/10337360/errors_20230103.log)

I do not know, maybe these errors are due to custom campaigns?

**Comment by fbef0102** [comment]
> 



> It worked for a few weeks without errors, but yesterday and today the errors appeared again:
> 
> L 01/02/2023 - 14:00:58: SourceMod error session started L 01/02/2023 - 14:00:58: Info (map "xmas_hotel") (file "/game/left4dead2/addons/sourcemod/logs/errors_20230102.log") L 01/02/2023 - 14:00:58: [SM] Exception reported: Client 3 is not connected L 01/02/2023 - 14:00:58: [SM] Blaming: AI_HardSI.smx L 01/02/2023 - 14:00:58: [SM] Call stack trace: L 01/02/2023 - 14:00:58: [SM] [0] SetUserFlagBits L 01/02/2023 - 14:00:58: [SM] [1] Line 442, includes\hardcoop_util.sp::CheatCommand L 01/02/2023 - 14:00:58: [SM] [2] Line 73, AI_HardSI.sp::Timer_ForceInfectedAssault L 01/02/2023 - 14:01:23: [SM] Exception reported: Client 5 is not connected L 01/02/2023 - 14:01:23: [SM] Blaming: AI_HardSI.smx L 01/02/2023 - 14:01:23: [SM] Call stack trace: L 01/02/2023 - 14:01:23: [SM] [0] SetUserFlagBits L 01/02/2023 - 14:01:23: [SM] [1] Line 442, includes\hardcoop_util.sp::CheatCommand L 01/02/2023 - 14:01:23: [SM] [2] Line 73, AI_HardSI.sp::Timer_ForceInfectedAssault L 01/02/2023 - 14:01:34: [SM] Exception reported: Client 1 is not connected L 01/02/2023 - 14:01:34: [SM] Blaming: AI_HardSI.smx L 01/02/2023 - 14:01:34: [SM] Call stack trace: L 01/02/2023 - 14:01:34: [SM] [0] SetUserFlagBits L 01/02/2023 - 14:01:34: [SM] [1] Line 442, includes\hardcoop_util.sp::CheatCommand L 01/02/2023 - 14:01:34: [SM] [2] Line 73, AI_HardSI.sp::Timer_ForceInfectedAssault L 01/02/2023 - 14:01:42: [SM] Exception reported: Client 14 is not connected L 01/02/2023 - 14:01:42: [SM] Blaming: AI_HardSI.smx L 01/02/2023 - 14:01:42: [SM] Call stack trace: L 01/02/2023 - 14:01:42: [SM] [0] SetUserFlagBits L 01/02/2023 - 14:01:42: [SM] [1] Line 442, includes\hardcoop_util.sp::CheatCommand L 01/02/2023 - 14:01:42: [SM] [2] Line 73, AI_HardSI.sp::Timer_ForceInfectedAssault L 01/02/2023 - 14:08:04: Error log file session closed.
> 
> Full logs: [errors_20230102.log](https://github.com/fbef0102/L4D2-Plugins/files/10337359/errors_20230102.log) [errors_20230103.log](https://github.com/fbef0102/L4D2-Plugins/files/10337360/errors_20230103.log)
> 
> I do not know, maybe these errors are due to custom campaigns?

[AI_HardSI.zip](https://github.com/fbef0102/L4D2-Plugins/files/10337718/AI_HardSI.zip)

**Comment by SefoNotasi** [comment]
Thank you. Put it on the server, I'll report in a couple of weeks about the result.

> > I do not know, maybe these errors are due to custom campaigns?
> 
> [AI_HardSI.zip](https://github.com/fbef0102/L4D2-Plugins/files/10337718/AI_HardSI.zip)
