### ISSUE TITLE
l4d2_skill_detect报错

### ISSUE THREAD

**Issue by LindaFelicia** [fbef0102/L4D2-Plugins#13]
L 01/30/2023 - 14:43:32: SourceMod error session started
L 01/30/2023 - 14:43:32: Info (map "contra3d05") (file "/home/steam/l4d2/left4dead2/addons/sourcemod/logs/errors_20230130.log")
L 01/30/2023 - 14:43:32: [SM] Exception reported: Invalid edict (2650 - 2650)
L 01/30/2023 - 14:43:32: [SM] Blaming: l4d2_skill_detect.smx
L 01/30/2023 - 14:43:32: [SM] Call stack trace:
L 01/30/2023 - 14:43:32: [SM]   [0] GetEdictClassname
L 01/30/2023 - 14:43:32: [SM]   [1] Line 3542, l4d2_skill_detect.sp::IsWitch
L 01/30/2023 - 14:43:32: [SM]   [2] Line 2086, l4d2_skill_detect.sp::OnTakeDamageByWitch
L 01/30/2023 - 14:43:40: [SM] Exception reported: Invalid edict (2650 - 2650)
L 01/30/2023 - 14:43:40: [SM] Blaming: l4d2_skill_detect.smx
L 01/30/2023 - 14:43:40: [SM] Call stack trace:
L 01/30/2023 - 14:43:40: [SM]   [0] GetEdictClassname
L 01/30/2023 - 14:43:40: [SM]   [1] Line 3542, l4d2_skill_detect.sp::IsWitch
L 01/30/2023 - 14:43:40: [SM]   [2] Line 2086, l4d2_skill_detect.sp::OnTakeDamageByWitch
L 01/30/2023 - 14:44:22: Error log file session closed.

**Comment by fbef0102** [comment]
[l4d2_skill_detect.zip](https://github.com/fbef0102/L4D2-Plugins/files/10533726/l4d2_skill_detect.zip)

**Comment by LindaFelicia** [comment]
谢谢，这版本解决了
