### ISSUE TITLE
当管理员在生还者

### ISSUE THREAD

**Issue by hanxiaoas** [fbef0102/L4D2-Plugins#16]
当管理员在生还者时如何设置可以见到发光

**Comment by fbef0102** [comment]
你在說哪一個插件?

**Comment by hanxiaoas** [comment]
spec cheat 这个

**Comment by fbef0102** [comment]
> 当管理员在生还者时如何设置可以见到发光

沒有设置

**Comment by 1795868827** [comment]
你好大佬我想找你制作插件
微信：q1795868827
QQ：1795868827

**Comment by fbef0102** [comment]
參考"[此插件](https://github.com/fbef0102/Game-Private_Plugin/tree/main/Plugin_%E6%8F%92%E4%BB%B6/Nothing_Impossible_%E7%84%A1%E7%90%86%E6%94%B9%E9%80%A0%E7%89%88/l4d2_wallhack_cheat)"
