### ISSUE TITLE
l4d2_item_hint繁简中翻译反了

### ISSUE THREAD

**Issue by LindaFelicia** [fbef0102/L4D2-Plugins#17]
> 	"Announce_Spot_Marker (C)"
> 	{
> 		"#format"	"{1:N}"
> 		"en"		"({green}Spot{default}) {olive}{1}{default} marked a position"
> 		"chi"		"({green}標記{default}) {olive}{1}{default} 標記了一個位置"
> 		"zho"		"({green}标记{default}) {olive}{1}{default} 标记了一个位置"
> 	}
> 	
> 	"Announce_Spot_Marker"
> 	{
> 		"#format"	"{1:N}"
> 		"en"		"(Spot) {1} marked a position"
> 		"chi"		"(標記) {1} 標記了一個位置"
> 		"zho"		"(标记) {1} 标记了一个位置"
> 	}

**Comment by fbef0102** [comment]
謝謝糾正
