### ISSUE TITLE
l4d2_supply_woodbox

### ISSUE THREAD

**Issue by Unfellowed** [fbef0102/L4D2-Plugins#20]
Hi Harry! Which line in the .sp file should I edit so that the supply box spawns 7 different guns? (rifle, rifle_ak47, rifle_desert, autoshotgun, shotgun_spas, sniper_military, hunting_rifle).
My config:
`"l4d2_supply_woodbox_item_max" "7"`
`"l4d2_supply_woodbox_item_min" "7"`
`"l4d2_supply_woodbox_item_chance" "100,0,0,0,0"`
`"l4d2_supply_woodbox_drop_max" "1"`
`"l4d2_supply_woodbox_drop_min" "1"`

**Comment by fbef0102** [comment]
[l4d2_supply_woodbox.sp L428-L479](https://github.com/fbef0102/L4D2-Plugins/blob/master/l4d2_supply_woodbox/scripting/l4d2_supply_woodbox.sp#L428-L479)

**Comment by Unfellowed** [comment]
The supply box still doesn't spawn 7 different guns. :(
![Screenshot (94)](https://github.com/fbef0102/L4D2-Plugins/assets/115072518/a60a0e58-c9fe-4690-a13b-a48ec83f7f57)
![Screenshot (93)](https://github.com/fbef0102/L4D2-Plugins/assets/115072518/404b208c-5f5c-4566-aeb6-4e2ccf43b2e5)

**Comment by fbef0102** [comment]
That's not how this plugin supposed to work.....
It spawns 7 weapons from the box, but each weapon is **random**, not 7 different guns

```
l4d2_supply_woodbox_item_max "7"
l4d2_supply_woodbox_item_min "7"
```

**Comment by Unfellowed** [comment]
The plugin works perfectly. Thank you! 👍
