### ISSUE TITLE
l4d2_item_hint 提示文字是英文

### ISSUE THREAD

**Issue by IDFrom** [fbef0102/L4D2-Plugins#23]
这个插件可以生效，但是提示文字是英文，请问怎么修改

**Comment by fbef0102** [comment]
圖片中這些 Director Hint 的提示無法支援多語言翻譯

![image](https://github.com/fbef0102/L4D2-Plugins/assets/12229810/4b009951-41f0-4fed-af70-87bffbf0d28d)
![image](https://github.com/fbef0102/L4D2-Plugins/assets/12229810/60cbf64a-6e04-437a-a5a6-979ed92bd321)

如果你只想改成中文，請到源碼修改
[l4d2_item_hint.sp#L302-L373](https://github.com/fbef0102/L4D2-Plugins/blob/master/l4d2_item_hint/scripting/l4d2_item_hint.sp#L302-L373)
[l4d2_item_hint.phrases.txt#L51-L56](https://github.com/fbef0102/L4D2-Plugins/blob/master/l4d2_item_hint/translations/l4d2_item_hint.phrases.txt#L51-L56)

**Comment by IDFrom** [comment]
![test](https://github.com/fbef0102/L4D2-Plugins/assets/42457028/62c1e980-dcc7-4eee-bb44-6024eb3ab4a2)
你好，麻烦看下这个，这个应该是有中文的吧

**Comment by fbef0102** [comment]
沒有
