### ISSUE TITLE
'l4d2_item_hint' Language Phrase not found in 'Cold Front' custom campaign.

### ISSUE THREAD

**Issue by Hatsune-Imagine** [fbef0102/L4D2-Plugins#27]
哈利，我发现 l4d2_item_hint 在 Cold Front 这张地图会出现报错，报错原因是玩家标记的特感模型对应的 ItemPhrase 是空字符串。其他图从来没出现过这个错误，只有这张图会。我当时并不在伺服器里玩，是路人在里面玩，我也是之后检查伺服器日志的时候才发现的。我不确定是不是因为 Cold Front 地图作者加了一些自定义的模型，导致获取不到对应的 ItemPhrase。

以下是完整的 error 日志：
http://47.100.221.111:9000/l4d2-addons/sourcemod/logs/errors_20240304.log

**Comment by fbef0102** [comment]
已修復 謝謝回報

**Comment by fbef0102** [comment]
> 感谢修复，不过第881行是不是写错了，应该是Smoker，不是Witch
> 
> ```c
> case ZC_SMOKER:
> {
> 	sItemPhrase = "Witch";
> }
> ```

已修復

**Comment by Hatsune-Imagine** [comment]
哦还有一个之前的 草叉 的Phrase和英语翻译拼错了，是 Pitchfork ，之前错写成了 Pitckfork
第 365 行：
```c
g_smModelToName.SetString("models/weapons/melee/w_pitchfork.mdl", "Pitckfork");
```

**Comment by Hatsune-Imagine** [comment]
感谢~

**Comment by fbef0102** [comment]
> Pitchfork

看到了 [7e7a287](https://github.com/fbef0102/L4D2-Plugins/commit/7e7a287d7f5f29d64d325a6c482e8662bb1a1995)
