### ISSUE TITLE
l4d2_item_hint: Different languanges are hinted by diffrerent players using different default languages

### ISSUE THREAD

**Issue by deprid** [fbef0102/L4D2-Plugins#29]
For example:

- Player A (server host) use English language in Steam, the server displays Player A hint in English
- Player B use tchinese, the server shows Player B hint in tchinese

Expected result:

- The server should be displaying all hints in respective language used by a client
- In client side, the server displays all hints in English for Player A
- In client side, the server displays all hints in tchinese for Player B

Workaround: I removed all the lines containing `zho` and `chi` in `l4d2_skill_detect.phrases`, now all displayed hints are in English

In [Translations (SourceMod Scripting)](https://wiki.alliedmods.net/Translations_(SourceMod_Scripting)), it mentions

> As of SourceMod 1.1, there is a new preferred method of shipping translations. By default, the main translation file should only contain English phrases. Additional translations are made in separate files, under a folder named after the ISO language code in languages.cfg.

Perhaps the issue happens because the additional translations are not put in the respective folder?

**Comment by fbef0102** [comment]
> Workaround: I removed all the lines containing `zho` and `chi` in `l4d2_skill_detect.phrases`, now all displayed hints are in English

I am kind of confused, are you talking about l4d2_item_hint or l4d2_skill_detect?


> For example:
> 
> * Player A (server host) use English language in Steam, the server displays Player A hint in English
> * Player B use tchinese, the server shows Player B hint in tchinese
> 
> Expected result:
> 
> * The server should be displaying all hints in respective language used by a client
> * In client side, the server displays all hints in English for Player A
> * In client side, the server displays all hints in tchinese for Player B

Yes. unfortunately for now. the **instructor hint** can not be translated into respective language.
The instructor hint is l4d2 game build-in message, not the function from sourcemod.

The only solution is to display instructor hint in server language only (English) for all players only.

1.[l4d2_item_hint.sp#L1777](https://github.com/fbef0102/L4D2-Plugins/blob/master/l4d2_item_hint/scripting/l4d2_item_hint.sp#L1777)
  ```c
  FormatEx(sCaption, sizeof(sCaption), "%T", sItemPhrase, client);
  ```
===> 
  ```c
  FormatEx(sCaption, sizeof(sCaption), "%T", sItemPhrase, LANG_SERVER);
  ```

2.[l4d2_item_hint.sp#L1786](https://github.com/fbef0102/L4D2-Plugins/blob/master/l4d2_item_hint/scripting/l4d2_item_hint.sp#L1786)
  ```c
  FormatEx(sCaption, sizeof(sCaption), "%T", "Spot_Maker", client, client);
  ```
===> 
  ```c
  FormatEx(sCaption, sizeof(sCaption), "%T", "Spot_Maker", client, LANG_SERVER);
  ```

3.[l4d2_item_hint.sp#L1795](https://github.com/fbef0102/L4D2-Plugins/blob/master/l4d2_item_hint/scripting/l4d2_item_hint.sp#L1795)
  ```c
  FormatEx(sCaption, sizeof(sCaption), "%T", sItemPhrase, client);
  ```
===> 
  ```c
  FormatEx(sCaption, sizeof(sCaption), "%T", sItemPhrase, LANG_SERVER);
  ```

Perhaps I will update in the future.

**Comment by deprid** [comment]
> I am kind of confused, are you talking about l4d2_item_hint or l4d2_skill_detect?

Oh sorry, it's l4d2_item_hint.phrases

Let me try the new version
