### ISSUE TITLE
l4d2_item_hint: Survivor Marker is not enabled by default

### ISSUE THREAD

**Issue by deprid** [fbef0102/L4D2-Plugins#30]
There's no Survivor Marker configuration in `l4d2_item_hint.cfg` generated by SM like seen in 'ConVar' in https://github.com/fbef0102/L4D2-Plugins/tree/master/l4d2_item_hint

Do I need to copy the configuration lines to the `l4d2_item_hint.cfg` in order to enable 'Mark your teammates'?

**Comment by fbef0102** [comment]
Remove your cfg and restart server, let Server generates cfg again

**Comment by deprid** [comment]
> Remove your l4d2_item_hint.cfg and restart server, let Server generate l4d2_item_hint.cfg again.

Done that, but it's still the same, without Survivor Marker...

**Comment by fbef0102** [comment]
That probably means that plugin version not updated.
Type in server console to check
```c
sm plugins info l4d2_item_hint
```

**Comment by deprid** [comment]
> Filename: l4d2_item_hint.smx
  Title: L4D2 Item hint (When using 'Look' in vocalize menu, print corresponding item to chat area and make item glow or create spot marker/infeced maker like back 4 blood.)
  Author: BHaType, fdxx, HarryPotter
  Version: 3.0-2024/3/6
  URL: https://forums.alliedmods.net/showpost.php?p=2765332&postcount=30
  Status: running
  Timestamp: 03/07/2024 13:19:56
  Hash: 037f23c397322a4f04be4619d2f91c3c

Oh that's the issue, I was using the 'old' version though it's not that too old (Mar '24) lol. Starting v3.1 it adds Survivor marker.

I tried out the latest version v3.5, Survivor Marker worked flawlessly.
