### ISSUE TITLE
AI_HardSI: Bug in smoker's behavior

### ISSUE THREAD

**Issue by SefoNotasi** [fbef0102/L4D2-Plugins#31]
Smoker behaves very strangely with AI_HardSI plugin: after trying to smoke someone and failing - he stands still and stares at the player, allowing himself to be easily killed. Smoker starts to follow the player only if he moves far away, and then he stands and stares at the player again until his ability recharges, and so on.

I recorded a video with this problem:
https://youtu.be/Q3VO3w1CIwM

Even if you turn off smoker's improved behavior (AI_HardSI_Smoker_enable 0), he continues to behave this way. Only disabling the plugin completely returns the standard behavior of the smoker, when he starts to run away, hide or distract the player after a failed attack.

Is there any way to fix the smoker's behavior, so that after an unsuccessful attack he runs away instead of standing still?

I use the plugin with its standard configuration, there are no other plugins that change the behavior of the smoker.

**Comment by fbef0102** [comment]
In further investigation, I realise that it is the ```nb_assault``` cmd cause somker not trying to run away.
Will fix soon

**Comment by fbef0102** [comment]
Update AI_HardSI v1.9

**Comment by SefoNotasi** [comment]
> Update AI_HardSI v1.9

Tested it, it's fixed. Thank you very much.

**Comment by SefoNotasi** [comment]
> Update AI_HardSI v1.9

Oh, I forgot to ask one more question:

Do I need to add ConVars from the “Improve Infected” section to the server.cfg or are they set by the plugin automatically and don't need to be written in the server config?

I mean these ConVars:
```
// Smoker
// How much damage to the smoker makes him let go of his victim. (Default: 50)
sm_cvar tongue_break_from_damage_amount 250

// Start to shoot his tongue after 0.1 seconds (Default: 1.5)
sm_cvar smoker_tongue_delay 0.1

// Boomer
// How long an out-of-range Boomer will tolerate being visible before fleeing (Default: 1.0)
sm_cvar boomer_exposed_time_tolerance 1000.0

// How long the Boomer waits before he vomits on his target on Normal difficulty (Default: 1.0)
sm_cvar boomer_vomit_delay 0.1

// Hunter
// Range at which hunter prepares pounce	 (Default: 1000)
sm_cvar hunter_pounce_ready_range 1000

// Range at which hunter is committed to attack	 (Default: 75)
sm_cvar hunter_committed_attack_range 10000

// Range at which shooting a non-committed hunter will cause it to leap away (Coop/Realis, Default: 1000)
sm_cvar hunter_leap_away_give_up_range 0

// Maximum vertical angle hunters can pounce (Default: 45)
sm_cvar hunter_pounce_max_loft_angle 0

// AI Hunter skeet damage (Default: 50)
sm_cvar z_pounce_damage_interrupt 150

// Jockey
// AI Jockeys will move to attack survivors within this range (Default: 200)
sm_cvar z_jockey_leap_range 1000
```

**Comment by fbef0102** [comment]
> Do I need to add ConVars from the “Improve Infected” section to the server.cfg or are they set by the plugin automatically and don't need to be written in the server config?

set by the plugin automatically
