### ISSUE TITLE
Feature Request: Add back in AI "Campaign Hunter Leap Away Mechanic"

### ISSUE THREAD

**Issue by jimmycm123** [fbef0102/L4D2-Plugins#32]
In Coop gamemodes, the AI hunter is given an ability to leap away when shot at in order to counteract it being less smart than a human. Can you add this feature back in the mod as an optional cvar? I find it too easy to quickly kill hunters that are far away from me as they do not have this ability and quickly die. [I have a video showing the vanilla behavior of this hunter "leap away feature".](https://youtu.be/2-ntNElKTD0)

I tested it out and it seems to be directly connected to the nb_assault cmd that prevents the hunter from performing the leap away mechanic. If possible, it would be cool if you can add the leap away mechanic back in, while still keeping the hunter very aggressive and not waiting in ambush mode.

**Comment by fbef0102** [comment]
```nb_assault``` cmd would attact hunters
1. Not waiting in ambush mode 
2. Give up Leap Away ability and just pounce to attack

So if restore back Leap Away ability, he will wait in ambush mode again.
I updated [new version](https://github.com/fbef0102/L4D2-Plugins/tree/master/AI_HardSI), you can adjust cvars in cfg/AI_HardSI/aggressive_ai.cfg

```c
// Range at which hunter is committed to attack  (Default: 75)
hunter_committed_attack_range 75

// Range at which shooting a non-committed AI hunter will cause it to leap away (Coop/Realis, Default: 1000)
// 0=Disable leap away ability, >0: Restore back Leap Away ability and wait in ambush mode again.
hunter_committed_attack_range 1000
```
