### ISSUE TITLE
Feature Request: Add Special Infected AOE Versus Stumble

### ISSUE THREAD

**Issue by jimmycm123** [fbef0102/L4D2-Plugins#33]
This plugin is very good because it makes the game much harder. Can you also add the feature where Special Infected can stumble nearby survivors when they attack the survivors like in Versus Mode? An example of the feature is like [this video here](https://youtu.be/tgpxqiOQU9I?t=133), but I want it to also affect the Jockey pounce to make campaign/realism mode harder like versus mode. Thanks.

**Comment by fbef0102** [comment]
Use [official convar](https://developer.valvesoftware.com/wiki/List_of_L4D2_Cvars)
```
// duration of infected stumble by anything/l4dh staggerplayer
// duration of survivor stumble time by Hunter/Jockey
// default: 6.0 in coop, 0.9 in versus
sm_cvar z_max_stagger_duration 1.0

// Hunter/jockey stumble range
// default: 0 in coop, 160 in versus
sm_cvar z_pounce_stumble_radius 180
```

**Comment by jimmycm123** [comment]
Thanks! I didn't know about that official convar.
