### ISSUE TITLE
oksykh: 我是傻B QQ號: 3411099

### ISSUE THREAD

**Issue by oksykh** [fbef0102/L4D2-Plugins#35]
这个是个骗子，大家注意，千万不要买它的插件，收了钱就跑路。出了BUG不修复，找借口推脱，一直骂人。一定要在正规的网站上交易。草拟吗狗骗子。诈骗岛老出你这种诈骗犯，真丢tw的脸
![傑利鼠](https://github.com/user-attachments/assets/b3b46dc9-b07b-480c-8ffb-dcfddaa662a5)

**Comment by oksykh** [comment]
看你往哪里跑，狗杂碎

**Comment by fbef0102** [comment]
要不要測試? 快 一句話 孬種

**Comment by oksykh** [comment]
急了急了，狗骗子，死全家

**Comment by oksykh** [comment]
好好宣传一下你，我把聊天记录都贴出来到其他论坛了。让大家看看你这个骗子的嘴脸

**Comment by fbef0102** [comment]
很棒 
叫你測試不測試
叫你設置不設置
浪費我時間 

你只花十元就要我負責別人的插件問題
腦袋有洞

**Comment by fbef0102** [comment]
> 好好宣传一下你，我把聊天记录都贴出来到其他论坛了。让大家看看你这个骗子的嘴脸

去 我等你

**Comment by fbef0102** [comment]
快去

**Comment by fbef0102** [comment]
連接貼出來 大家來欣賞

**Comment by oksykh** [comment]
> 很棒 叫你測試不測試 叫你設置不設置 浪費我時間
> 
> 你只花十元就要我負責別人的插件問題 腦袋有洞
![IMG_1281](https://github.com/user-attachments/assets/e3ff6b50-b573-4691-b5f1-f154fa7324b8)
![IMG_1282](https://github.com/user-attachments/assets/e1716ca2-8550-466f-bb38-feb1e875ee48)


请不要说假话。100块钱到你这里就变成10块钱了？

**Comment by fbef0102** [comment]
你付我100元修復control_zombies.sp ?
白癡?

**Comment by oksykh** [comment]
幸亏老子及时止损。你这个狗骗子，骗100块钱给你全家买棺材吧

**Comment by fbef0102** [comment]
花了十元修復sm_pt
什麼時候變成100?

**Comment by fbef0102** [comment]
要貼連結了嗎 ?
要測了嗎?

**Comment by oksykh** [comment]
我就把这个帖子贴出来，让大家看~~看清你是个什么东西

**Comment by apples1949** [comment]
哥们，你能不能要点脸

**Comment by oksykh** [comment]
> 花了十元修復sm_pt 什麼時候變成100?

交易截图都在这里。你狡辩nm？

**Comment by apples1949** [comment]
来，我看看你是怎么说的

**Comment by fbef0102** [comment]
![image](https://github.com/user-attachments/assets/351df331-97d5-4b88-9b29-74b1b2c9f59a)
100元?100元?100元?100元?100元?

**Comment by fbef0102** [comment]
"馬的" 是語助詞啦 幹嗎那麼緊張
有罵到你人身攻擊嗎?

**Comment by oksykh** [comment]
> 哥们，你能不能要点脸

他pt没有修复，我就找他，结果被骂两次。也不给修复，然后直接删除我好友，这不是骗是什么？钱就这样打水漂了

**Comment by oksykh** [comment]
。你把骗我的钱都给我还回来，不然就一直这样挂着吧。你就找你的同温层报团取暖吧，反正我这个是给后来人看的

**Comment by fbef0102** [comment]
講 "馬的" 就算當罵你了喔= =
那我道歉行不 這句話我對不起

**Comment by apples1949** [comment]
> 。你把骗我的钱都给我还回来，不然就一直这样挂着吧。你就找你的同温层报团取暖吧，反正我这个是给后来人看的

我现在有理由怀疑你是不是华人，告诉你加个z就能解决的问题墨迹半天。不懂还觉得自己没问题？

**Comment by fbef0102** [comment]
> 。你把骗我的钱都给我还回来，不然就一直这样挂着吧。你就找你的同温层报团取暖吧，反正我这个是给后来人看的

可以 你先測試啊 
權限Z沒有解決問題 我退你10元
要不要

**Comment by qy087** [comment]
> 。你把骗我的钱都给我还回来，不然就一直这样挂着吧。你就找你的同温层报团取暖吧，反正我这个是给后来人看的

哥们你是中国人吗，插件群都在笑你看不懂中文了，本来就是写z权限要求简简单单收个十块钱完了

**Comment by oksykh** [comment]
> > 。你把骗我的钱都给我还回来，不然就一直这样挂着吧。你就找你的同温层报团取暖吧，反正我这个是给后来人看的
> 
> 出來面對啊 叫你測試不測試 讓你退錢又不願意了是吧

我出去吃饭了，哪像你这个网络废物，一天到晚挂在电脑上

**Comment by fbef0102** [comment]
> > > 。你把骗我的钱都给我还回来，不然就一直这样挂着吧。你就找你的同温层报团取暖吧，反正我这个是给后来人看的
> > 
> > 
> > 出來面對啊 叫你測試不測試 讓你退錢又不願意了是吧
> 
> 我出去吃饭了，哪像你这个网络废物，一天到晚挂在电脑上

好喔 孬種不敢測試打自己臉

**Comment by oksykh** [comment]
> > 。你把骗我的钱都给我还回来，不然就一直这样挂着吧。你就找你的同温层报团取暖吧，反正我这个是给后来人看的
> 
> 哥们你是中国人吗，插件群都难蚌你看不懂中文了，本来就是写z权限要求简简单单收个十块钱完了，你都会上gayhub连这点都不会吗？

钱收了，改了，没用。改了，没用～完了这货就开始骂人，还删好友

**Comment by oksykh** [comment]
> > > > 。你把骗我的钱都给我还回来，不然就一直这样挂着吧。你就找你的同温层报团取暖吧，反正我这个是给后来人看的
> > > 
> > > 
> > > 出來面對啊 叫你測試不測試 讓你退錢又不願意了是吧
> > 
> > 
> > 我出去吃饭了，哪像你这个网络废物，一天到晚挂在电脑上
> 
> 好喔 孬種不敢測試打自己臉

我测了，没用，懂？你他妈直接删好友了，我怎么告诉你没用？

**Comment by fbef0102** [comment]
行 重加 你發我gamedata

**Comment by fbef0102** [comment]
你QQ黑名單 我怎麼加
![image](https://github.com/user-attachments/assets/13140fd9-2f6e-4b95-9ffa-57427856d1df)

**Comment by fbef0102** [comment]
傻B: 我有bug
我: 你測試
傻B: 我有bug
我: 你測試
傻B: 我有bug
我: 你測試
傻B: 我有bug
我: 你測試
傻B: 我有bug

我: 刪除好友
傻B: 騙子

**Comment by fbef0102** [comment]
那就快點
來加QQ 我到是看想你這小白怎麼測試
![image](https://github.com/user-attachments/assets/718b6ec6-fcac-44fc-a524-e8e97095a145)

**Comment by fbef0102** [comment]
自己說不用測試的, hello?
![image](https://github.com/user-attachments/assets/9eca5955-101d-44cd-ba11-7d97d91f0fe4)

**Comment by fbef0102** [comment]
> > 傻B: 我有bug 我: 你測試 傻B: 我有bug 我: 你測試 傻B: 我有bug 我: 你測試 傻B: 我有bug 我: 你測試 傻B: 不測試
> > 我: 刪除好友 傻B: 騙子
> 
> 孩子，真是对你无语了，测试也测试了，测不通过我就问你怎么写权限，你说写z ，我写了也测了还不行，你就骂人，完了骂完人就直接删我好友，结果你还在这里强词夺理说我没测，能不能改一下你这种喜欢骗人和胡说八道的性格？你真是搞笑～帖子就挂在这里吧～

你的其他論壇貼文呢? 放完屁就想跑啊 孬種

**Comment by fbef0102** [comment]
小白: 我根本不會這玩意
![image](https://github.com/user-attachments/assets/4bdd0e24-23d1-447c-8c6d-781be2cf4b92)

**Comment by fbef0102** [comment]
花錢大爺 
什麼時候有空加QQ 來測試?
我準備好要退你10元了

**Comment by oksykh** [comment]
> 花錢大爺 什麼時候有空加QQ 來測試? 我準備好要退你10元了

你是眼睛瞎了还是煞笔了？不是你说了，在外面陪老婆逛街吃饭。真是个臭屌丝，一天到晚就知道玩电脑。

**Comment by oksykh** [comment]
> 花錢大爺 什麼時候有空加QQ 來測試? 我準備好要退你10元了

Loser

**Comment by fbef0102** [comment]
等你回來 可以吧
我們測試 別拐彎抹角

10元就要我負責全部代碼
好威 你去其他論壇問看看有哪個大老願意接你的問題

**Comment by oksykh** [comment]
> 等你回來 可以吧 我們測試 別拐彎抹角
> 
> 10元就要我負責全部代碼 好威 你去其他論壇問看看有哪個大老願意接你的問題

放你妈个狗屁，你哪个逼眼看到老子让你负责全部代码

**Comment by fbef0102** [comment]
> > 花錢大爺 什麼時候有空加QQ 來測試? 我準備好要退你10元了
> 
> 你是眼睛瞎了还是煞笔了？不是你说了，在外面陪老婆逛街吃饭。真是个臭屌丝，一天到晚就知道玩电脑。

要陪就陪 
一小時前還有時間po文
還以為你很閒

**Comment by oksykh** [comment]
> 等你回來 可以吧 我們測試 別拐彎抹角
> 
> 10元就要我負責全部代碼 好威 你去其他論壇問看看有哪個大老願意接你的問題

该你妈一点点东西都改不好，一个小功能让你说这全部代码

**Comment by fbef0102** [comment]
> > 等你回來 可以吧 我們測試 別拐彎抹角
> > 10元就要我負責全部代碼 好威 你去其他論壇問看看有哪個大老願意接你的問題
> 
> 该你妈一点点东西都改不好，一个小功能让你说这全部代码

沒錯 指令也是我負責的 
即使小白看不懂如何設置權限也沒關係 10元問大佬

**Comment by apples1949** [comment]
蚌埠住了

**Comment by oksykh** [comment]
> > > 等你回來 可以吧 我們測試 別拐彎抹角
> > > 10元就要我負責全部代碼 好威 你去其他論壇問看看有哪個大老願意接你的問題
> > 
> > 
> > 该你妈一点点东西都改不好，一个小功能让你说这全部代码
> 
> 沒錯 指令也是大老負責的 即使小白看不懂如何設置權限也沒關係 10元問大佬 即使插件不是大老寫的 小白我付錢最大爺

10块钱不是你骗人的资本懂吗？你要解决不了就说解决不了，没必要骂人➕好友。

**Comment by cH1yoi** [comment]
怪幽默的这哥们儿...

**Comment by fbef0102** [comment]
> > > > 等你回來 可以吧 我們測試 別拐彎抹角
> > > > 10元就要我負責全部代碼 好威 你去其他論壇問看看有哪個大老願意接你的問題
> > > 
> > > 
> > > 该你妈一点点东西都改不好，一个小功能让你说这全部代码
> > 
> > 
> > 沒錯 指令也是大老負責的 即使小白看不懂如何設置權限也沒關係 10元問大佬 即使插件不是大老寫的 小白我付錢最大爺
> 
> 10块钱不是你骗人的资本懂吗？你要解决不了就说解决不了，没必要骂人➕好友。

能解決啦 哈哈 搞笑
現在問題無法解決的原因在你 先生

等你回來 加QQ 我們來和平地測試

**Comment by oksykh** [comment]
> > > 等你回來 可以吧 我們測試 別拐彎抹角
> > > 10元就要我負責全部代碼 好威 你去其他論壇問看看有哪個大老願意接你的問題
> > 
> > 
> > 该你妈一点点东西都改不好，一个小功能让你说这全部代码
> 
> 沒錯 指令也是大老負責的 即使小白看不懂如何設置權限也沒關係 10元問大佬 即使插件不是大老寫的 小白我付錢最大爺

建议你把你们群里的所有人都拉过来～就这么几个人来，这骂，太少了

**Comment by oksykh** [comment]
> > > > > 等你回來 可以吧 我們測試 別拐彎抹角
> > > > > 10元就要我負責全部代碼 好威 你去其他論壇問看看有哪個大老願意接你的問題
> > > > 
> > > > 
> > > > 该你妈一点点东西都改不好，一个小功能让你说这全部代码
> > > 
> > > 
> > > 沒錯 指令也是大老負責的 即使小白看不懂如何設置權限也沒關係 10元問大佬 即使插件不是大老寫的 小白我付錢最大爺
> > 
> > 
> > 建议你把你们群里的所有人都拉过来～就这么几个人来，这骂，太少了
> 
> 我幹嗎拉群 不是你自己說要去論壇貼我的事情 既然你認為你自己是對的 那就越多人來越看越好

那就挂在这里太热闹吧，反正我无所谓

**Comment by fbef0102** [comment]
到底要不要加QQ測試? 是個男人就趕快說
我在等您回來

**Comment by qy087** [comment]
> > > > > > 等你回來 可以吧 我們測試 別拐彎抹角
> 
> > > > > > 10元就要我負責全部代碼 好威 你去其他論壇問看看有哪個大老願意接你的問題
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 该你妈一点点东西都改不好，一个小功能让你说这全部代码
> 
> > > > 
> 
> > > > 
> 
> > > > 沒錯 指令也是大老負責的 即使小白看不懂如何設置權限也沒關係 10元問大佬 即使插件不是大老寫的 小白我付錢最大爺
> 
> > > 
> 
> > > 
> 
> > > 建议你把你们群里的所有人都拉过来～就这么几个人来，这骂，太少了
> 
> > 
> 
> > 我幹嗎拉群 不是你自己說要去論壇貼我的事情 既然你認為你自己是對的 那就越多人來越看越好
> 
> 
> 
> 那就挂在这里太热闹吧，反正我无所谓

第 一 次 接 触，cvar没写好就是bug也不找找自己的原因哈利都重复跟你说了方法就是不听既然看不懂中文那也只有加钱咯，不过还是建议你还是看得懂中文再来带节奏吧

**Comment by fbef0102** [comment]
> > 哥们，你能不能要点脸
> 
> ![Screenshot 2024-11-20 171659](https://private-user-images.githubusercontent.com/34675267/388027010-28a890e7-c501-4353-8cea-aa8dadaf454b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDE4NzcsIm5iZiI6MTczMjEwMTU3NywicGF0aCI6Ii8zNDY3NTI2Ny8zODgwMjcwMTAtMjhhODkwZTctYzUwMS00MzUzLThjZWEtYWE4ZGFkYWY0NTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDExMTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMWQ1YTc2MzMwNDUwYjQzMjA1NGVhMTJmYjZlOTg4MWZmOWMwY2FkMWUwZWUzMTUyZGVmNTY1ODYwOThiZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WE8_BtuQXtf9RMNH60EU4vdS6YocBm1oBTaPjaxhnaU) 他乱骂人在先，完了直接删好友

關於 "馬的" 我認為是表達無奈的語助詞
無罵你爹娘與人身攻擊之意圖
兩岸用詞用語不同 導致誤會
我在這裡慎重跟你道歉 不該罵 "馬的"

**Comment by OmuroHanako** [comment]
前来文明观猴.jpg

**Comment by txuk1x** [comment]
别侮辱猴，这不纯傻逼？懒得喷😅

**Comment by oksykh** [comment]
> 别侮辱猴，这不纯傻逼？懒得喷😅

我也觉得我是纯傻逼哦

**Comment by fbef0102** [comment]
> > 别侮辱猴，这不纯傻逼？懒得喷😅
> 
> 我也觉得你是纯傻逼哦
沒心解決一個小問題

**Comment by oksykh** [comment]
> > > 别侮辱猴，这不纯傻逼？懒得喷😅
> > 
> > 
> > 我也觉得你是纯傻逼哦
> 
> 沒心解決一個小問題

行了~删除了~以后再也不见

**Comment by fbef0102** [comment]
這是你QQ吧 有空要解決問題再來找我
![image](https://github.com/user-attachments/assets/bddf5781-df2e-403e-978c-2493f1a7c45a)

**Comment by fbef0102** [comment]
退款 給其他大佬接手他的問題
![image](https://github.com/user-attachments/assets/559a0b7a-de73-4c65-9010-587fed4ac404)
