### ISSUE TITLE
Simplified Chinese translation of the cvar description text for the plugin L4D2_Buy_Store

### ISSUE THREAD

**Issue by apples1949** [fbef0102/L4D2-Plugins#4]
`g_PlayerRequired = CreateConVar("sm_shop_player_require", "4", "多少真实的感染者和生还者才能激活插件", FCVAR_NOTIFY, true, 1.0);
g_hCookiesCachedEnable = CreateConVar("sm_shop_CookiesCached_enable", "1", "如果为1则使用CookiesCached储存玩家数据,否则玩家离开服务器数据就莫得了", FCVAR_NOTIFY, true, 0.0, true, 1.0);
g_BoomerKilled = CreateConVar("sm_shop_boomkilled", "10", "Giving money for killing a boomer", FCVAR_NOTIFY, true, 1.0);
g_ChargerKilled = CreateConVar("sm_shop_chargerkilled", "30", "Giving money for killing a charger", FCVAR_NOTIFY, true, 1.0);
g_SmokerKilled = CreateConVar("sm_shop_smokerkilled", "20", "Giving money for killing a smoker", FCVAR_NOTIFY, true, 1.0);
g_HunterKilled = CreateConVar("sm_shop_hunterkilled", "20", "Giving money for killing a hunter", FCVAR_NOTIFY, true, 1.0);
g_JockeyKilled = CreateConVar("sm_shop_jockeykilled", "25", "Giving money for killing a jockey", FCVAR_NOTIFY, true, 1.0);
g_SpitterKilled = CreateConVar("sm_shop_spitterkilled", "10", "Giving money for killing a spitter", FCVAR_NOTIFY, true, 1.0);
g_hTankHurt = CreateConVar("sm_shop_tank_hurt", "40", "给坦克多少伤害得到1金钱", FCVAR_NOTIFY, true, 1.0);
g_WitchKilled = CreateConVar("sm_shop_witchkilled", "80", "Giving money for killing a witch", FCVAR_NOTIFY, true, 1.0);
g_ZombieKilled = CreateConVar("sm_shop_zombiekilled", "1", "Giving money for killing a zombie", FCVAR_NOTIFY, true, 1.0);
g_hHealTeammate = CreateConVar("sm_shop_heal_teammate", "100", "用医疗包治疗队友给多少钱", FCVAR_NOTIFY, true, 1.0);
g_hDefiSave = CreateConVar("sm_shop_defi_save", "200", "电击队友复活奖励多少钱", FCVAR_NOTIFY, true, 1.0);
g_hHelpTeammate = CreateConVar("sm_shop_help_teammate_save", "30", "救下队友的奖励 (除开被舌头吊起来的情况)", FCVAR_NOTIFY, true, 1.0);
g_hIncapSurvivor = CreateConVar("sm_shop_infected_survivor_incap", "30", "感染者玩家击倒幸存者给多少钱 (除了舌头捆倒幸存者)", FCVAR_NOTIFY, true, 1.0);
g_hKillSurvivor = CreateConVar("sm_shop_infected_survivor_killed", "100", "感染者玩家击杀幸存者给多少钱", FCVAR_NOTIFY, true, 1.0);
g_hTKSurvivorEnable = CreateConVar("sm_shop_survivor_TK_enable", "1", "如果为1，友伤扣钱黑，黑1血扣多少钱，如果为0则不扣钱", FCVAR_NOTIFY, true, 0.0, true, 1.0);
g_hGascanMapOff = CreateConVar("sm_shop_gascan_map_off",        "c1m4_atrium,c6m3_port,c14m2_lighthouse",        "这些地图用不能购买油桶, 用逗号分割(无空格). (0=全部的地图, 空格 = 无).", FCVAR_NOTIFY );
g_hColaMapOff =        CreateConVar("sm_shop_cola_map_off",        "c1m2_streets",        "这些地图用不能购买可乐瓶, 用逗号分割(无空格). (0=全部的地图, 空格 = 无).", FCVAR_NOTIFY );
g_hMaxJumpLimit  =        CreateConVar("sm_shop_special_max_jump_limit",        "3",        "特殊物品空中跳跃最大次数", FCVAR_NOTIFY, true, 1.0);
g_hInfiniteAmmoTime  =        CreateConVar("sm_shop_special_infinite_ammo_time",        "15",        "特殊物品无限子弹能持续多久", FCVAR_NOTIFY, true, 1.0);
g_hStageComplete =        CreateConVar("sm_shop_stage_complete", "400",        " 小章节结束给生还者多少钱.", FCVAR_NOTIFY, true, 1.0);
g_hFinalMissionComplete =        CreateConVar("sm_shop_final_mission_complete", "3000",        "救援成功给存活生还者的钱", FCVAR_NOTIFY, true, 1.0);
g_hWipeOutSurvivor =        CreateConVar("sm_shop_final_mission_lost", "300",        "团灭生还者扣多少钱以及有感染者玩家灭团生还者给多少钱", FCVAR_NOTIFY, true, 1.0);
g_hDeadEyeTime  =        CreateConVar("sm_shop_special_dead_eyes_time",        "60",        "特殊物品心灵透视能持续多久", FCVAR_NOTIFY, true, 1.0);
g_hInfectedShopEnable =        CreateConVar("sm_shop_infected_enable", "1",        "如果为1，则启动感染者购买菜单", FCVAR_NOTIFY, true, 0.0, true, 1.0);
g_hInfectedShopTime = CreateConVar("sm_shop_infected_wait_time", "10", "感染者玩家必须等到幸存者离开安全区至少多少秒后才能购买物品。(0=感染者的商店随时可用)", FCVAR_NOTIFY, true, 0.0);
g_hInfectedShopColdDown =        CreateConVar("sm_shop_infected_cooltime_block", "30.0",        "感染者购买冷却时间(0=无)", FCVAR_NOTIFY, true, 0.0);
g_hSurvivorShopColdDown =        CreateConVar("sm_shop_survivor_cooltime_block", "5.0",        "在玩家购买物品后，多长时间才能再次购买（秒）。(0=关闭)。", FCVAR_NOTIFY, true, 0.0);
g_hImmuneDamageTime =        CreateConVar("sm_shop_special_immune_everything_time",        "8",        "特殊物品伤害免疫能持续多久", FCVAR_NOTIFY, true, 1.0);
g_hInfectedShopTankLimit =        CreateConVar("sm_shop_infected_tank_limit",        "1",        "场上坦克数量超过多少数量后就不能购买坦克了(0=不能购买坦克)", FCVAR_NOTIFY, true, 0.0);
g_hInfectedShopWitchLimit =        CreateConVar("sm_shop_infected_witch_limit","4",        "场上女巫数量超过多少数量后就不能购买女巫了(0=不能购买女巫)", FCVAR_NOTIFY, true, 0.0);
g_hWitchSpawnSafetyRange = CreateConVar("sm_shop_infected_witch_spawn_safety_range", "1250", "感染者玩家可以在离幸存者多远的地方购买女巫.", FCVAR_NOTIFY, true, 100.0);
g_hWitchKillTime = CreateConVar("sm_shop_infected_witch_lifespan", "180", "在多少秒后踢掉女巫(在此插件中只删除玩家购买的女巫)", FCVAR_NOTIFY, true, 1.0);
g_hFreezeTime =        CreateConVar("sm_shop_special_freeze_time",        "6",        "特殊物品冰冻世界能持续多久", FCVAR_NOTIFY, true, 1.0);
g_hMaxMoney =        CreateConVar("sm_shop_max_moeny_limit",        "32000",        "最大可持有金钱数量(当服务器换图或者玩家离开服务器才能保存金钱到数据库)", FCVAR_NOTIFY, true, 1.0);
g_hNotifyKillInfectedType = CreateConVar("sm_shop_kill_infected_announce_type",        "1", "改变击杀敌人给予金钱信息的显示方式(0: 不显示, 1:在聊天框中, 2: 在提示框中, 3: 在屏幕中心？)", FCVAR_NOTIFY, true, 0.0, true, 3.0);`

**Comment by fbef0102** [comment]
Why you close, 我看得懂中文

**Comment by apples1949** [comment]
本來是想將自己翻譯cvar說明發上來 發完就感覺唐突了 打開一看格式錯亂了 只能關掉 git沒用幾次給您造成麻煩了
