### ISSUE TITLE
l4d2_explosive_cars_unload "" don't work

### ISSUE THREAD

**Issue by BioHazardN7** [fbef0102/L4D2-Plugins#9]
On the maps "White Forest" from the Steam Workshop, I wanted to disable this plugin.
I write "l4d2_explosive_cars_unload "wfp1_track,wfp2_horn,wfp3_mill"" in config, but this don't work
Screens: [1](https://images2.imgbox.com/c9/6d/cBPZNCLO_o.png), [2](https://images2.imgbox.com/7f/4f/dGFwy1rZ_o.png), [3](https://images2.imgbox.com/15/a0/Jqu5J9Pt_o.png), [4](https://images2.imgbox.com/8b/49/mDKe8sgU_o.png)

**Comment by fbef0102** [comment]
where do you write l4d2_explosive_cars_unload "wfp1_track,wfp2_horn,wfp3_mill"?
which config?

**Comment by BioHazardN7** [comment]
The config "l4d2_explosive_cars.cfg" was created automatically when I first entered the game in the catalog "d:\Steam\steamapps\common\Left 4 Dead 2\left4dead2\cfg\sourcemod\l4d2_explosive_cars.cfg".

**Comment by fbef0102** [comment]
I just tested and it works in my computer..
what is your version?
can you send me your sourcemod\l4d2_explosive_cars.cfg?

**Comment by BioHazardN7** [comment]
The plugin version was 1.9 (it was the latest version at the time). After updating to 2.0 everything works fine. I'm sorry to trouble you.
